baseURL: https://priceless-chandrasekhar-ed7379.netlify.app/
languageCode: en
DefaultContentLanguage: en
title: Website of Ibsen Melo
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes

markup:
  goldmark:
    renderer:
      unsafe: true
